baseURL = "http://vovalabs.com/"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "vovalabs - Acoustics and Design"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Featured Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Contact"
url = "contact"
weight = 5

# Sitemap Menu
[[menu.sitemap]]
name = "Contact me"
url = "contact"
weight = 1

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © vovalabs 2023"
footerLogo = "images/contact/logo.png"
# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/7yJmmsd"
googleAnalytics = "G-7CVVVTMTTG"
logo = "images/site-navigation/logo2.png"

[params.address]
address = ""
email = "info@vovalabs.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+(448) 833 5272 332"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons

enableRobotsTXT = true